DROP ROLE test;
CREATE ROLE test WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN ENCRYPTED PASSWORD '*';
DROP ROLE sa;
CREATE ROLE sa WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD '123456'; 
CREATE LANGUAGE plpgsql;
