DROP ROLE test;
CREATE ROLE test WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN ENCRYPTED PASSWORD '*';
DROP ROLE sa;
CREATE ROLE sa WITH SUPERUSER CREATEDB CREATEROLE LOGIN ENCRYPTED PASSWORD '123456'; 
DROP ROLE bookkeeper;
CREATE ROLE bookkeeper WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN ENCRYPTED PASSWORD '123';
DROP ROLE seller;
CREATE ROLE seller WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN ENCRYPTED PASSWORD '123';
CREATE LANGUAGE plpgsql;
